var catergoryMap = new Map();

catergoryMap.set("INCOME", ["FUTURICE", "GEHALT"]);
catergoryMap.set("GROCERIES", [
  "EDEKA",
  "REWE SAGT DANKE",
  "PENNY",
  "NETTO MARKEN-DISCOU",
  "ALNATURA",
  "VOLLCORNER",
  "BASIC AG MUENCHEN",
  "DENNS BIOMARKT",
  "ALDI",
  "LIDL"
]);
catergoryMap.set("DRUGSTORE", ["DM DROGERIEMARKT", "ROSSMANN"]);
catergoryMap.set("APPARTMENT", [
  "STACHETER VERMOEGENSVERWALTUNG",
  "MIETE VON JULE",
  "SWM VERSORGUNGS GMBH",
  "M-NET TELEKOMMUNIKATIONS GMBH",
  "ARD ZDF DRADIO BEITRAGSSERVICE",
  "NEBENKOSTEN"
]);
catergoryMap.set("CLOTHES", [
  "COS",
  "WEEKDAY",
  "H+M",
  "HM MUENCHEN",
  "HMHENNESMAU",
  "ZALANDO SE",
  "ARKET",
  "PLANET SPORTS GMBH",
  "PLANETSPORT",
  "KAUF DICH GLUECKLICH MUENCH",
  "LUDWIG BECK",
  "21SPORTSGROUP GMBH",
  "GLOBETROTTER",
  "KAUFGLUECK",
  "ASOSCOMLTD",
  "BELLROY",
  "ASKET",
  "TOPSHOP",
  "SPEEDO",
  "ODERSO"
]);
catergoryMap.set("PUBLIC_TRANSPORT", [
  "MVG",
  "DB VERTRIEB GMBH",
  "STUTTGARTER STRASSENBAHNEN",
  "WIENER LINIEN",
  "S-BAHN-BERLIN GMBH",
  "DB AUTOMATEN"
]);
catergoryMap.set("TRAVEL", [
  "DB BAHN",
  "LUFTHANSA",
  "HOTEL",
  "AIRBNB",
  "SAS",
  "CONDOR",
  "TRAINLINE",
  "MEININGER",
  "EUROWINGS",
  "URLAUB",
  "BAYERN TICKET"
]);
catergoryMap.set("BOOKS", ["HUGENDUBEL", "ISARFLIMMERN", "BUCHHANDLUNG"]);
catergoryMap.set("INSURANCE", [
  "DOCURA",
  "AXA",
  "GOTHAER",
  "HUK-COBURG",
  "TECHNIKER KRANKENKASSE"
]);
catergoryMap.set("ATM", ["BARGELDAUSZAHLUNG", "STADTSPARKASSE"]);
catergoryMap.set("BAR_CAFE", [
  "CAFE",
  "COFFEE",
  "KAFFEE",
  "RESTAURANT",
  "TRATTORIA",
  "BURGER",
  "BURRITO",
  "AROMA KAFFEEBAR",
  "GOLDMARIE",
  "HANS IM GLUECK",
  "HEINRICH MATTERS",
  "FRISCHES BIER",
  "LA SOPHIA GMBH",
  "CONDESA GMBH",
  "NANA SPEISEBAR",
  "MIYO BOBLINGEN",
  "BRAUKUNST BERLIN",
  "KAISERGARTEN"
]);
catergoryMap.set("SAVINGS", ["RUECKLAGEN", "SPARPLAN"]);

export default catergoryMap;
